/**
 * LinkedIn copy, generated from the career fact base.
 *
 *   bun run linkedin            # → out/linkedin.md
 *
 * LinkedIn has no API for editing your own profile, so this writes paste-ready
 * plain text — one block per field, with the character count against the
 * field's limit. The run fails if any block exceeds its limit.
 */
import { identity, linkedin, roles, projects, skills } from '../src/data/career/facts';
import { formatMonth, pick } from '../src/data/career/resolve';

const ROOT = new URL('..', import.meta.url).pathname;
const OUT = `${ROOT}out/linkedin.md`;

/** Field limits as LinkedIn enforces them in the profile editor. */
const LIMIT = { headline: 220, about: 2600, position: 2000, project: 2000 } as const;

const blocks: string[] = [];
let over = 0;

function block(title: string, text: string, limit: number) {
  const len = [...text].length;
  const flag = len > limit ? `  ⚠ OVER by ${len - limit}` : '';
  if (len > limit) over++;
  blocks.push(`## ${title}  (${len}/${limit})${flag}\n\n\`\`\`text\n${text}\n\`\`\``);
}

block('Headline', linkedin.headline, LIMIT.headline);
block('About', linkedin.about, LIMIT.about);

for (const role of roles) {
  role.positions.forEach((position, i) => {
    const newer = role.positions[i - 1];
    const start = i === role.positions.length - 1 ? role.start : position.since;
    const end = newer ? newer.since : role.end;
    const lines =
      i === 0
        ? [
            ...(role.context ? [pick(role.context, 'linkedin')] : []),
            // Rank 3 is filler by definition — the first thing any channel cuts.
            ...role.highlights
              .filter((h) => h.rank < 3)
              .map((h) => `• ${h.lead}: ${pick(h.text, 'linkedin')}`),
          ]
        : [linkedin.earlierPositions[`${role.id}:${position.title}`] ?? ''].filter(Boolean);
    block(
      `${position.title} — ${role.company} · ${role.location} (${formatMonth(start)} – ${end ? formatMonth(end) : 'present'})`,
      lines.join('\n') || '(no description)',
      LIMIT.position,
    );
  });
}

for (const project of projects) {
  block(
    `Project: ${project.name} (${project.year}) — ${project.href}`,
    `${pick(project.text, 'linkedin')}\n\nStack: ${project.stack.join(', ')}`,
    LIMIT.project,
  );
}

blocks.push(
  `## Skills (add in this order, top 5 get pinned)\n\n${skills
    .flatMap((group) => group.items)
    .map((s) => `- ${s}`)
    .join('\n')}`,
);

const header = `# LinkedIn — ${identity.name}\n\nGenerated by \`bun run linkedin\` from src/data/career. Paste field by field; do not edit here.\n`;
await Bun.$`mkdir -p ${ROOT}out`.quiet();
await Bun.write(OUT, [header, ...blocks].join('\n\n') + '\n');
console.log(`${OUT.replace(ROOT, '')}: ${blocks.length} blocks${over ? `, ${over} OVER LIMIT` : ''}`);
process.exit(over ? 1 : 0);
